## Streszczenie {-}

Głównym celem pracy jest analiza Kołobrzeskiego Roweru Miejskiego w kontekście generowanego przez rower miejski natężenia ruchu rowerowego w poszczególnych stacjach oraz analiza dokumentów strategicznych w Kołobrzegu. 
Analizę natężenia rowerowego wykonano między innymi za pomocą języka R, a dane pobrano za pośrednictwem Nextbike API.
Analiza dokumentów strategicznych obejmowała analizę studium uwarunkowań i kierunków zagospodarowania przestrzennego, strategie rozwoju SmartCity oraz analizę SWOT dotyczącą polityki przestrzennej i infrastruktury rowerowej.
Ponadto przeprowadzono badanie ankietowe na próbie ponad 100 osób dotyczące roweru miejskiego w Kołobrzegu i kołobrzeskiej infrastruktury rowerowej oraz przedstawiono charakterystykę miasta Kołobrzeg, 

Wynikiem analiz jest projekt koncepcji zagospodarowania, która zakłada powstanie nowych stacji Kołobrzeskiego Roweru Miejskiego, które przedstawiono na mapach wykonanych za pomocą oprogramowania QGis oraz za pośrednictwem platformy System Informacji Przestrzennej Miasta Kołobrzeg.

Słowa kluczowe: System roweru publicznego, infrastruktura rowerowa, badanie ankietowe, SmartCity, język R

## Abstract {-}

The main aim of this paper is to analyse Kolobrzeg's Urban Bicycle in the context of bicycle traffic generated by the bicycle at individual stations and to analyse strategic documents in Kolobrzeg. 
The analysis of the bicycle traffic volume was performed using the R language, among others, and the data was downloaded via Nextbike API.
The analysis of strategic documents included an analysis of the spatial development conditions and directions, SmartCity development strategies, and a SWOT analysis of spatial policy and cycling infrastructure.
In addition, a survey was carried out on a sample of more than 100 people on urban cycling in Kołobrzeg and the Kołobrzeg cycling infrastructure, and the characteristics of the city of Kołobrzeg were presented, 

The result of the analyses is a draft development concept, which assumes the creation of new Kolobrzeg City Bicycle stations, which are presented on maps created using the QGis software and via the Spatial Information System platform of the City of Kolobrzeg.

Keywords: Bike-sharing system, bicycle infrastructure, questionnaire survey, SmartCity, R language

\newpage

\setstretch{1.2}\sf\tighttoc\doublespacing
