# Analiza dokumentów planistycznych i strategicznych {#polityka}

##	Studium uwarunkowań i kierunków zagospodarowania przestrzennego {#studium}

Aktualne studium uwarunkowań i kierunków zagospodarowania przestrzennego miasta Kołobrzeg zostało uchwalone przez rade miasta dnia 30 marca 2021 roku. 
W części opisowej dokumentu znajdują się informacje dotyczące kształtowania systemu ścieżek rowerowych, zadań systemu komunikacji rowerowej, cech dróg rowerowych, celów układu komunikacji rowerowej oraz powiązania komunikacji rowerowej z komunikacją zbiorową.

W części dotyczącej kształtowania systemu ścieżek rowerowych wymienia się potrzebę powstania systemu ścieżek rowerowych dla mieszkańców oraz turystów pragnących aktywnie spędzać czas.  Docelowa długość takiego systemu ścieżek ma wynosić około 40 km, przy czym według studium obecnie wynosi około 15 km i planowana jest budowa 2km odcinka od ulicy Arciszewskiego do Grzybowa oraz od ulicy Brzeskiej do Ustronia Morskiego.
Zauważono, że mimo optymalnej wielkości oraz układu miasta to transport rowerowy w Kołobrzegu jest wykorzystywany głównie w celach rekreacyjnych, a nie jako codzienny środek transportu.

Głównym zadaniem systemu komunikacji rowerowej jest założenie, że 70% celów i źródeł podróży mieszkańców miasta Kołobrzeg powinno być dostępnych w ramach systemu rowerowego, który jest dobrze zintegrowany z otaczającą go siecią drogową.
System ma się składać z układu tras głównych, które spinają najważniejsze punkty w mieście, tras zbiorczych, wraz z przyjaznym dla ruchu rowerowego śródmieściem oraz z tras dojazdowych i lokalnych.
Rowerowe trasy główne i zbiorcze powinny być oddzielone pasem zieleni.
System rowerowy powinien wpisywać się w projekt europejskiej sieci długodystansowych dróg rowerowych Eurovello.

Wśród cech dróg rowerowych wymieniono odpowiednią nawierzchnię (asfalt, bitumiczną), która umożliwia bezpieczną podróż rowerem o prędkości 30-40 km/godzinę oraz wyznaczenie sieci rowerowej przez praki oraz nadrzeczne bulwary. 
Stwierdzono, że do sytemu rowerowego można włączyć istniejące alejki, ścieżki gruntowe, chodniki wzdłuż głównych ulic i pasaże. 

Celem układu komunikacji rowerowej w Kołobrzegu jest (@studium_uwarunkowan):

- zwiększenie mobilności wszystkich grup wiekowych (dzieci, osoby starsze)

- poprawa mobilności osób bez samochodów i mieszkańców obszarów gorzej, obsługiwanych
przez komunikację zbiorową,

- zmniejszenie emisji toksycznych (dwutlenek węgla), zmniejszenie zanieczyszczeń środowiska,

- poprawa bezpieczeństwa na drogach (poprzez prowadzenie ruchu rowerowego na wydzielonych
ścieżkach),

- wykorzystanie roweru w krótkich podróżach po mieście,

- oszczędność miejsc parkingowych dla uczestników ruchu (wskaźnik: 10 rowerów na 1 miejscu
parkingowym). 

Powiązanie komunikacji rowerowej z komunikacją zbiorową według studium jest realizowane za pomocą bezpiecznego i komfortowego dojazdu rowerem do głównych przystanków komunikacji zbiorowej oraz do dworców kolejowych, możliwością bezpiecznego przechowywania rowerów na przystankach, możliwością przewozu rowerów środkami komunikacji zbiorowej oraz polityką taryfową sprzyjającą rowerzystom.

## Strategia rozwoju SmartCity Kołobrzeg {#strategia_roz}

W strategii rozwoju kwestie komunikacji uznawane są za jedno z głównych wyzwań rozwojowych miasta.
związane jest to z bardzo dużym obciążeniem lokalnego układu komunikacyjnego przez indywidualny transport kołowy co nastąpiło wraz z sukcesem turystycznym miasta i ma szczególne znaczenie w sezonie turystycznym.
Według strategii rozwoju długość ścieżek rowerowych w 2018 roku zgodnie z danymi z Głównego Urzędu Statystycznego wynosi 40km, co jest sprzeczne z informacjami przedstawionymi w studium uwarunkowań i kierunków zagospodarowania przestrzennego.

Jednym z priorytetów wymienianych w dokumencie jest *miasto przyjaznej mobilności* gdzie celem jest rozwijanie zrównoważonego i niskoemisyjnego systemu mobilności, opartego na komunikacji publicznej miasta, regionu i kraju, rozwiniętym systemie komunikacji rowerowej oraz na systemach zarządzania. Współgra to z jednym z zadań, które dotyczy stworzenia partycypacyjnego przewodnika miejskiego, który będzie służył między innymi promocji zrównoważonej mobilności w ruchu turystycznym – sposób formułowania opisów 
przemieszczania się powinien w pierwszej kolejności zachęcać do ruchu pieszego, rowerowego 
czy korzystania z transportu publicznego.
Zadanie to zostało zrealizowane poprzez udostępnienie aplikacji *Kołobrzeg: RE:GENERACJA*, będącej mobilnym przewodnikiem miejskim, która dostępna jest na smartphone-ach.

W perspektywie realizacji strategii w ramach spójnej i inteligentnej polityki przestrzennej i mieszkaniowej wszystkie kluczowe skupiska zabudowy powinny być położone w zasięgu transportu publicznego i powiązane z siecią dróg dla rowerów.

Sieć rowerowa włączona jest w priorytet miasta ekologicznego w ramach zadania zarządzanie strategiczne błękitno-zieloną siecią dla Kołobrzegu, która oprócz korzyści przyrodniczych ma się wiązać z funkcją społeczno-edukacyjną. 

Zwraca się także uwagę na poprawę warunków oświetleniowych rowerzystów w ramach zadania inteligentne i energooszczędne oświetlenie.

Komunikacja rowerowa jest postrzegana w strategii jako jedna z alternatyw (obok transportu miejskiego) dla transportu kołowego.
Uważa się, że należy wzmocnić atrakcyjność komunikacji rowerowej (oprócz rozwoju dróg rowerowych i stacji np. poprzez program zachęt dla pracowników sektora publicznego w zamian za korzystanie z roweru lub transportu publicznego w dojazdach do miejsca pracy), która już teraz posiada duży potencjał, który należy dalej rozwijać poprzez rozwój ścieżek rowerowych oraz usług roweru miejskiego, w tym dążenie do rozszerzenia tych usług w wymiarze funkcjonalnym na sąsiednie gminy w ramach Nadmorskiego Obszaru Funkcjonalnego co jest celem zadania spójna i zintegrowana polityka mobilności dla Kołobrzegu oparta o dane.

Zadanie to jest realizowane, dostępny jest obecnie dobrze rozwinięty system informacji przestrzennej miasta Kołobrzeg dostępny na dedykowanej stronie, gdzie znajdują się dane przestrzenne oraz serwisy mapowe - gdzie można znaleźć miedzy innymi model 3D miasta, ortofotomapy, mapy dotyczące planowania przestrzennego, infrastruktury czy też dostępną mapę strefy płatnego parkowania lub mapę potencjału solarnego dachów.
Możliwość płatności za bilet komunikacji miejskiej oraz parkingowy dostępny jest za pomocą aplikacji Skycash co także jest z zgodne z koncepcją mobilność jako usługa (@smartcity).

Strategia stawia także tezę, że inicjatywa Kołobrzeskiego Roweru Miejskiego powinna być stale rozwijana, zarówno w aspekcie zwiększania zasięgu sieci stacji, jak i jej zagęszczenia.

## Analiza SWOT w kontekście polityki przestrzennej i infrastruktury rowerowej

#### *Strengths* (Mocne strony)

- wielkość tkanki miejskiej Kołobrzegu jest optymalna dla ruchu rowerowego

- stosunkowo rozwinięta sieć ścieżek rowerowych

- funkcjonujący Kołobrzeski Rower Miejski

- szlak rowerowy R10 będący częścią europejskiej sieci dróg rowerowych EuroVelo

- wieloletnie działania władz miejskich w kierunku transportu rowerowego (Studium Rowerowe)

- koncepcja Kołobrzeg Smart City

- istniejący system informacji przestrzennej Kołobrzegu

- aplikacja Kołobrzeg RE:GENERACJA


#### *Weaknesses* (Słabe strony)

- obciążenie układu komunikacyjnego przez transport kołowy 

- zjawisko kongestii, zwłaszcza w czasie sezonu turystycznego

- brak spójności między strategią a studium

- stan ścieżek rowerowych

- mała gęstość stacji Kołobrzeskiego Roweru Miejskiego

- niska skuteczność promocji korzystania z transportu rowerowego wśród turystów


#### *Opportunities* (Szanse)

- dofinansowanie w ramach Europejskiego Zielonego Ładu

- rozwój współpracy z gminami ościennymi

- wzrastająca świadomość ekologiczna

- inwestycje w ramach rządowego funduszu Polski Ład


#### *Threats* (Zagrożenia)

- zagrożenia obcięcia budżetu związane z pandemią COVID-19 

- wysoka inflacja

- niepewna sytuacja międzynarodowa 

- wzrost kosztów towarów na rynku międzynarodowym

- zaburzenia łańcuchu dostaw



